experiment:
  name: logreg_baseline
  mode: train

data:
  test_size: 0.2
  random_state: 42

model:
  type: logreg

search:
  n_trials: 4
  timeout_seconds: 0

  # continous ranges
  C_min: 1.0e-3
  C_max: 100.0
  tol_min: 1.0e-6
  tol_max: 1000.0
  max_iter_min: 200
  max_iter_max: 5000

  # categorical choices
  class_weight: [null, "balanced"]
  fit_intercept: [true, false]
  warm_start: [true, false]